[tool.black]
line-length = 79
target-version = ['py313']
include = '\.pyi?$'
exclude = '''
/(
    \.git
    |__pycache__
    |\.venv
    |venv
    |\.env
    |migrations
    |\*.pyc
)/
'''
skip-magic-trailing-comma = false

[tool.isort]
profile = "google"